config/routes.rb
MetaTicTacToe::Application.routes.draw do
  
  resources :games, only: [:new, :update, :show] do
    get 'expire', action: :expire, on: :member
  end

  get 'rules', to: 'pages#rules'

  post 'pusher/auth', to: 'pages#pusher_auth'

  root to: 'pages#index'
end

app/models/game.rb
class Game < ActiveRecord::Base

  validates_presence_of   :short_code

  validates_presence_of   :game_state

  after_initialize   :default_values
  after_find         :unserialize_state
  before_save        :serialize_state

  def default_values
    return unless self.short_code.nil?

    self.short_code = SecureRandom.hex
    self.turn = "X"
    # Initialize an empty array
    self.game_state = self.build_board
    self.overall_score = [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '] 
  end



  def state
    # Return the array of arrays that represents the state
    g_state = {
      turn: self.turn,
      overall_score: self.overall_score,
      board: self.game_state,
      finished: self.finished?,
      winner: self.winner
    }
    g_state
  end

  def board
    @board ||= self.build_board
  end


  def unserialize_state
    self.game_state = ActiveSupport::JSON.decode(self.game_state)
    self.overall_score = ActiveSupport::JSON.decode(self.overall_score)
  end

  def serialize_state
    self.game_state = self.game_state.to_json
    self.overall_score = self.overall_score.to_json
  end

  # private

  def build_board
    single_grid = [ 
      [' ', ' ', ' '], 
      [' ', ' ', ' '], 
      [' ', ' ', ' '] 
    ]

    [1,1,1].fill do |r|
      [1,1,1].fill do |c|
        single_grid
      end
    end
  end

end

app/models/game_state.rb
class GameState

  def initialize(state=nil)
    @grids = [0,0,0].fill do |i|
      [0,0,0].fill{|x| Grid.new}
    end

    if state
      self.load_state state
    end
    
  end


  # Is the game over?
  def over?

  end

  # Get the winner
  def winner

  end

  # Export the state to be loaded into the database
  def export

  end

  # Return the game state as a json object
  def to_json

  end


  private

  def load_state(state)
  end



end

app/models/grid.rb
# This represents a single game (3x3 grid)

class Grid

  def initialize(state=nil)
    @squares = [nil,nil,nil].fill [nil,nil,nil]

    if state
      # Load the state
      self.load_state state
    end
  end

  # Move (:X, :O, nil)
  def move(row, col, letter=nil)
    @squares[row][col] = letter
  end

  # Is this board full?
  def full?
    @squares.flatten.index(nil).nil?
  end

  # Who won?
  def winner
    @winner ||= find_winner
  end

  def to_a

  end


  private

  def load_state(state)

  end

  # Check if a specific player has won
  def winner?(letter=:X)
    win_arr = [letter, letter, letter]

    # check rows
    return true unless @squares.index(win_arr).nil?

    # check columns
    return true unless @squares.index(win_arr).nil?
  end


  def find_winner
    winning_patterns =
      [[(/OOO....../), [0,1,2], :O], [(/...OOO.../), [3,4,5], :O],
       [(/......OOO/), [6,7,8], :O], [(/O..O..O../), [0,3,6], :O],
       [(/.O..O..O./), [1,4,7], :O], [(/..O..O..O/), [2,5,8], :O],
       [(/O...O...O/), [0,4,8], :O], [(/..O.O.O../), [2,4,6], :O],
       [(/XXX....../), [0,1,2], :X], [(/...XXX.../), [3,4,5], :X],
       [(/......XXX/), [6,7,8], :X], [(/X..X..X../), [0,3,6], :X],
       [(/.X..X..X./), [1,4,7], :X], [(/..X..X..X/), [2,5,8], :X],
       [(/X...X...X/), [0,4,8], :X], [(/..X.X.X../), [2,4,6], :X]
     ]

    flatboard = @squares.flatten.map do |square|
      case square
      when nil then ' '
      when :X then 'X'
      when :O then 'O'
      end
    end

    array = winning_patterns.find { |p| p.first =~ flatboard.join }
    if array
      # @winner = (array.last === :X) ? 'X' : 'O'
      # @win_moves = array[1]
      return array.last
    end
    return nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update, :expire]

  # GET /games/1
  # GET /games/1.json
  def show
    @game_details = {
      expire_path: expire_game_url(@game)
    }
  end

  # GET /games/new
  def new
    @game = Game.new
    @game.save!

    redirect_to @game
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update

    @game.turn = params[:game][:turn]
    @game.finished = params[:game][:finished]
    @game.winner = params[:game][:winner]
    @game.overall_score = ActiveSupport::JSON.decode(params[:game][:overall_score])
    @game.game_state = ActiveSupport::JSON.decode(params[:game][:game_state])

    respond_to do |format|
      if @game.save
        format.json { head :no_content }
      else
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def expire

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:short_code, :game_state, :overall_score, :turn)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def rules
  end

  def pusher_auth
    response = Pusher[params[:channel_name]].authenticate(params[:socket_id],{
      :user_id => rand(1..1000000),
      :user_info => {
        :name => 'blah'
      }
    })
    render :json => response
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title(page_title)
    content_for(:title) { h(page_title.to_s) }
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :short_code %><br>
    <%= f.text_field :short_code %>
  </div>
  <div class="field">
    <%= f.label :game_state %><br>
    <%= f.text_area :game_state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_game_board.html.erb
<section id="gameboard">


  <% 3.times do |board_row| %>
  <div class="row">
    <% 3.times do |board_col| %>
<% grid_pos = 0 %>    
    <div class="span2" data-board-pos="<%= "#{board_row},#{board_col}" %>">
      <table class="table table-bordered table-condensed" 
        data-board-row="<%= board_row %>"
        data-board-col="<%= board_col %>"
        >
        <tbody>
        <% 3.times do |row| %>
        <tr>
          <% 3.times do |col| %>
          <td 
            width="33%"
            data-board-row="<%= board_row %>"
            data-board-col="<%= board_col %>"
            data-row="<%= row %>"
            data-col="<%= col %>"
            data-grid-pos="<%= grid_pos %>"
            data-coord="<%= row %>,<%= col %>"
            data-board-coord="<%= board_row %>,<%= board_col %>"
            >
            <a href="#" class="place-marker">X</a>
          </td>
          <% grid_pos = grid_pos + 1 %>
          <% end %>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
  <% end %>


</section>

app/views/games/_overall_scoreboard.html.erb
<% overall_pos = 0 %>
<table class="table table-bordered table-condensed overall-board">
  <tbody>
  <% 3.times do |row| %>
  <tr>
    <% 3.times do |col| %>
    <td 
      width="33%"
      data-row="<%= row %>"
      data-col="<%= col %>"
      data-pos="<%= overall_pos %>"
      >
      &nbsp;
    </td>
    <% overall_pos = overall_pos + 1 %>
    <% end %>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/expire.html.erb
<h1>Game Expired</h1>

<div class="alert">
It looks like nothing was happening in your game for awhile, so we closed the connection.
<br/><br/>
Don't worry, you can always <%= link_to 'return to your game', @game %> if you want.
</div>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Short code</th>
      <th>Game state</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.short_code %></td>
        <td><%= game.game_state %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<% title 'Play Game' %>
<% content_for :before_scripts do %>
<%= javascript_include_tag "http://js.pusher.com/2.1/pusher.min.js" %>
<script>

var PUSHER = new Pusher('<%= Pusher.key %>');

</script>
<% end %>


<div class="row">
  <div class="span6">
    <%= render "game_board" %>
  </div>

  <div class="span6 board-stats">
    <div id="wait_overlay" class="alert"><span>Waiting for another player to join!</span></div>

    <div class="row">
      <div class="span4">
        <h2>Player: <span class="player-letter">X</span>
          <small>(<a href="#" data-action="switch">switch</a>)</small>
        </h2>

        <div class="alert alert-success" id="turn_notice">
          It's your turn! Make your move
        </div>

        <button class="btn" data-action="save">Save</button>
      </div>
      <div class="span2">
        <h4>Overall Score</h4>
        <%= render "overall_scoreboard" %>
      </div>
    </div>




  </div>
</div>




<script>

window.GAME_DETAILS = <%= @game_details.to_json.html_safe %>;

initializeGameState('<%= @game.id %>', <%= @game.state.to_json.html_safe %>);

</script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title><%= content_for?(:title) ? yield(:title) : "Home" %> | Meta Tic-Tac-Toe</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= yield :before_scripts %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield :extra_scripts %>

</head>
<body id="pagebody">
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<header>

  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Meta Tic-Tac-Toe</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to 'New Game', new_game_path %></li>
              
              <% if controller.controller_name == "games" && controller.action_name == "show" %>
              <li class="active"><%= link_to 'Play!', @game %></li>
              <% end %>

              <li><%= link_to 'Rules', rules_path %></li>
            </ul>

            <ul class="nav pull-right">
              <li><%= link_to 'About', 'https://github.com/webdestroya/meta-tic-tac-toe/blob/master/README.md' %></li>
              <li><%= link_to 'Source', 'https://github.com/webdestroya/meta-tic-tac-toe' %></li>
              <li><%= link_to 'Bugs', 'https://github.com/webdestroya/meta-tic-tac-toe/issues' %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

</header>

<div class="container-fluid" id="content">

  <div class="container">

  <% if content_for?(:page_heading) || content_for?(:title) %>
  <div class="page-header"><h1>
    <% if content_for?(:page_heading) %>
      <%= yield :page_heading %>
    <% elsif content_for?(:title) %>
      <%= yield :title %>
    <% end %>
  </h1></div>
  <% end %>
    
  <%= yield %>

  </div>

</div>

<div class="clear"></div>

<footer>
  <div class="container">
  <aside>&nbsp;</aside>
  <div class="noprint row-fluid">
    <div class="span12" style="text-align:center;">
      Meta-Tic-Tac-Toe app by <a href="http://www.mitchdempsey.com/?utm_source=meta-tic-tac-toe&utm_medium=website&utm_campaign=footer">Mitch Dempsey</a>
    </div>
  </div>
</div>
</footer>




<% if ::Rails.env.eql?("production") %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-18627936-5', 'mitchdempsey.com');
  ga('send', 'pageview');

</script>
<% end %>

</body>
</html>

app/views/pages/index.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
  <h1>Meta Tic-Tac-Toe</h1>
  <p>Play a game of Meta Tic-Tac-Toe with a friend!</p>
  <p>
    <%= link_to 'Start a new game!', new_game_path, class: 'btn btn-primary btn-large btn-success' %>
  </p>
</div>

<!-- Example row of columns 
<div class="row">
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div>
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
 </div>
  <div class="span4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div>
</div>
-->

app/views/pages/rules.html.erb
<h1>Meta Tic-Tac-Toe Rules</h1>


<h4>Board</h4>
<p>The game board consists of a three-by-three grid of tic-tac-toe boards.</p>

<h4>Winning</h4>
<p>
  The goal of the game is to win three of the tic-tac-toe boards in the same row, column, or diagonal - a meta tic-tac-toe.
</p>

<p>Each individual tic-tac-toe board is won by the usual rules of tic-tac-toe.</p>

<h4>Play</h4>
<p>
  On the first move, a player may place a mark in any of the available slots. 
</p>

<p>
  After the first move, however, players may only make marks in the tic-tac-toe board whose position in the game board is the same as the position in the smaller tic-tac-toe board of the previous player's mark.
</p>

<p>
  For example, if the first player were to play in the top left corner of the center tic-tac-toe board, the second player would have to place his or her next mark in one of the slots of the top left tic-tac-toe board.
</p>

<p>
  Note that it is perfectly legal (and, in some cases, a good strategy) to send your opponent to a tic-tac-toe board that has already been won.
</p>


<div class="alert alert-info">
These rules have been taken from Greg Owen's <a href="https://github.com/GregOwen/Meta-Tic-Tac-Toe">Meta-Tic-Tac-Toe</a> page.
</div>